targets = ["x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-freebsd"]

[[files]]
local = "resources/auth.json.pkg"
remote = "ETC/intecture/auth.json"

[scripts]
build = "sed 's~<CFGPATH>~/usr/local/etc/intecture~' resources/auth.json > resources/auth.json.pkg"
install = "mkdir /usr/local/etc/intecture/certs"
