[package]
name = "intecture-auth"
version = "0.0.1"
authors = [ "Peter Hayes <peter.hayes@betweenlines.co.uk>" ]
license = "MPL-2.0"
description = "Authentication for Intecture infrastructure. Intecture is the developer friendly, multi-lingual configuration management tool."
keywords = ["intecture", "auth"]
homepage = "https://intecture.io"
repository = "https://github.com/intecture/auth"

[dev-dependencies]

tempdir = "0.3.*"

[dependencies]

czmq = { git = "https://github.com/petehayes102/rust-czmq.git", tag = "0.0.4" }
docopt = "0.6"
rustc-serialize = "0.3.*"
zdaemon = { git = "https://github.com/betweenlines/zdaemon.git" }
zmq = { git = "https://github.com/petehayes102/rust-zmq.git", branch = "tmp-master" }

[lib]

name = "inauth_client"
path = "src/client.rs"

[[bin]]

name = "inauth_server"
path = "src/server.rs"

[[bin]]

name = "inauth_cli"
path = "src/cli.rs"
