#!/bin/sh
#
# inauth - this script starts and stops the inauth daemon
#
# chkconfig:   - 85 15
# description:  Auth component for Intecture infrastructure
# processname: inauth
# config:      /etc/intecture/auth.json

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

inauth="/usr/bin/inauth"
config="/etc/intecture/auth.json"
prog="inauth"
pidfile="/var/run/$prog.pid"

start() {
    [ -x $inauth ] || exit 5
    [ -f $config ] || exit 6

    echo -n $"Starting $prog: "

    # Check if daemon already started
    local pids=$(pidof $prog)
    if [ -n "$pids" ]; then
        echo -n "$prog (pid $pids) is already running" && warning
        echo
        return 0
    fi

    nohup "$inauth" >/dev/null 2>&1 &
    RETVAL=$?

    # Write pid to file and print status
    [ $RETVAL -eq 0 ] && echo $! > $pidfile && success || failure
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 7
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
